server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://userservice
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=2

            - id: activity
              uri: lb://activity
              predicates:
                - Path=/api/activity/**
              filters:
                - StripPrefix=2

            - id: activity-ai
              uri: lb://activity-ai
              predicates:
                - Path=/api/ai/**
              filters:
                - StripPrefix=2

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
