server:
  port: 8080

spring:
  application:
    name: apiGateway

  cloud:
    gateway:
      routes:
        - id: userservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2

        - id: activity
          uri: http://localhost:8082
          predicates:
            - Path=/api/activity/**
          filters:
            - StripPrefix=2

        - id: activity_AI
          uri: http://localhost:8083
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=2

eureka:
  client:
    enabled: true
